### ISSUE TITLE
I installed everything, but still it says no bark for some reason...

### ISSUE THREAD

**Issue by OlliSagi** [wsippel/bark_tts#11]
ERROR:Failed to load the extension "{name}".
Traceback (most recent call last):
  File "C:\Users\Documents\aistuff\oobabooga_windows\text-generation-webui\modules\extensions.py", line 34, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "C:\Users\Documents\aistuff\oobabooga_windows\text-generation-webui\extensions\bark_tts\script.py", line 6, in <module>
    from bark import SAMPLE_RATE, generate_audio, preload_models
ModuleNotFoundError: No module named 'bark'

**Comment by Ph0rk0z** [comment]
pip install git+https://github.com/suno-ai/bark.git

inside of the environment where you run textgen

**Comment by LeMaireBrando** [comment]
I am getting the same error.  It seems it installs `suno-bark` rather than a `bark` module.

**Comment by Ph0rk0z** [comment]
If you are on windows maybe it is installing into the wrong env. suno-bark is just the name of the pip

**Comment by bobsixtyfour** [comment]
If your using oobabooga, run the cmd_windows.bat, and THEN run:
cd text-generation-webui\extensions
git clone https://github.com/wsippel/bark_tts.git
pip install -r bark_tts/requirements.txt

**Comment by artokun** [comment]
It's kinda lame but they hide a lot of the conda magic in the oobabooga one-click-installer

at the end of the file just comment out `python webui.py` and drop in the pip install command in there like so

```sh
# start_linux.sh
...


# setup installer env
#python webui.py <--- comment this out first
pip install -r ./text-generation-webui/extensions/bark_tts/requirements.txt # <-- paste this in and run script again
echo
echo "Done!"
```

**Comment by CodeNinjasV** [comment]
I am running into this issue too, any updates on a solution?

**Comment by karmarcharger** [comment]
> I am running into this issue too, any updates on a solution?

https://github.com/wsippel/bark_tts/issues/11#issuecomment-1556109991

for windows edit the start_windows.bat and switch it back after you see bark is installed

**Comment by luthis1124** [comment]
I just did a reinstall of oobabooga and then this repo, everything worked. I'm on Linux though

**Comment by MarkPhsd** [comment]
Also having a problem with the same issue. Using Windows 10. Using the one click installer.

**Comment by Promootheus** [comment]
Got the same error as the OP, running on linux. Folled the instructions and tried the suggestions here also.
Edit: Just fixed it by running the oobabooga update script follwed by pip uninstall suno-bark, then repeat the pip install -r requirements.txt
