### ISSUE TITLE
Old audio messages are autoplayed when page is refreshed

### ISSUE THREAD

**Issue by allenhs** [wsippel/bark_tts#16]
Describe the bug
When using Bark tts whenever a new message is generated by the model, all of the previous audio messges play together at the same time. This doesn't happen with Silero

Is there an existing issue for this?
 I have searched the existing issues
Reproduction
Dont know how to reproduce it

Screenshot
No response

Logs
no errors, this is the only thing:

System Info
Fedora, Nvidia 4090

**Comment by wsippel** [comment]
Thanks for the heads up, some changes in Oobabooga broke my extension. Should be fixed now.

**Comment by allenhs** [comment]
I can confirm it is fixed now, thanks!
