### ISSUE TITLE
TypeError: preload_models() got an unexpected keyword argument 'text_use_gpu'

### ISSUE THREAD

**Issue by MiniCoperations** [wsippel/bark_tts#2]
Hi there, just tried to update to the newer version that has the config support and I cannot get the extension to load because of the titled error. Here is the section of the console as it tries to load the extension:
```
Loading the extension "bark_tts"... [nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Thomas\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

Loading Bark models...
Fail.
Traceback (most recent call last):
  File "C:\Programs\GPT\text-generation-webui\modules\extensions.py", line 20, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "C:\Programs\GPT\text-generation-webui\extensions\bark_tts\script.py", line 79, in <module>
    preload_models(
TypeError: preload_models() got an unexpected keyword argument 'text_use_gpu'
```
This is with the default config file setup.
I have never gotten it to load the extension past this, though the webui can still launch but the extension is not present since it didn't load.

Troubleshooting Tried:
I have tried toggling the value between True and False, true and false & 1 and 0.
I have ran the webui as normal and as an administrator.
I have reinstalled the extension twice.

All changes have had no effect on the loading.

I'm not sure if this is something I have caused or not but I cannot figure out how to get it to load.

My System:
CPU: AMD Ryzen 3900x
RAM: 32GB 3200MHz
GPU: Nvidia RTX 3080 10GB
OS: Windows 11

**Comment by wsippel** [comment]
I think you have a slightly older version of Bark installed, you need the very latest version. Try `pip uninstall suno-bark`, then repeat the `pip install -r requirements.txt` step. That's sadly something that tends to happen with bleeding edge software, Bark's API isn't stable yet and I try to implement new features as they become available. I should probably add something about this to the readme...

**Comment by MiniCoperations** [comment]
Ah yes that did fix it, thanks!
I will make sure I completely reset it like this again in the future.

And yes you are using my post haha, I felt honored when I noticed I was reading my own writing after I skipped to the code section. Good work on the extension so far!
