### ISSUE TITLE
only install berk_tts

### ISSUE THREAD

**Issue by kalle07** [wsippel/bark_tts#25]
well runing new oobbooga on win10 

i installed bark
and if i start this error:

2023-11-15 21:46:42 INFO:Loading the extension "bark_tts"...
[nltk_data] Downloading package punkt to extensions/bark_tts/...
[nltk_data]   Package punkt is already up-to-date!

Loading Bark models...
e:\text-generation-webui\installer_files\env\lib\site-packages\torch\nn\utils\weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Traceback (most recent call last):
  File "e:\text-generation-webui\server.py", line 238, in <module>
    create_interface()
  File "e:\text-generation-webui\server.py", line 142, in create_interface
    extensions_module.create_extensions_block()  # Extensions block
  File "e:\text-generation-webui\modules\extensions.py", line 192, in create_extensions_block
    extension.ui()
  File "e:\text-generation-webui\extensions\bark_tts\script.py", line 243, in ui
    chat.save_persistent_history, gradio('history', 'character_menu', 'mode'), None).then(
AttributeError: module 'modules.chat' has no attribute 'save_persistent_history'
...

**Comment by wsippel** [comment]
The `save_persistent_history` issue should be fixed.

**Comment by kalle07** [comment]
sry, what sould i doo with that infornation ?

**Comment by wsippel** [comment]
That's the error you ran into. Update the extension and things should (hopefully) work.
