### ISSUE TITLE
One word at a time....

### ISSUE THREAD

**Issue by OrphBean** [wsippel/bark_tts#7]
My install seems to regenerate the whole sequence at every new word. Anyone have a fix?

So it'll output
"So
So how
So how are
So how are you" etc etc

I am running the default install on Win 11, with a 4090

**Comment by wsippel** [comment]
I've seen this happen randomly, but haven't found a way to reliably reproduce it, which makes it quite difficult to debug. It doesn't even make sense to me to begin with, as my tokenizer never splits by word, only by sentence.

**Comment by Ph0rk0z** [comment]
Does that to me as well.. I have streaming on and it will just encode every time a word is generated. Would be cool if there was an option for it to wait until generation is finished.
![tts](https://github.com/wsippel/bark_tts/assets/59298527/dfc66d1d-33bc-459d-ae60-c8ed6507d1a8)

**Comment by qingtom** [comment]
same issue. the plugin regenerate the whole sentence every time a token is generated, which make the conversation very slow.

any solution to this?

I have config the `tokenize = False`, which I guess to config the action.

**Comment by Ph0rk0z** [comment]
Well.. one is to turn off streaming.

**Comment by wsippel** [comment]
The extension should properly disable streaming now. Feel free to reopen the issue if it somehow doesn't.
